// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2WRSrNT_amxU0SECjNsGtO2bUX-W7LjI',
    appId: '1:388102120008:web:3aa8514ef164abe9baae7d',
    messagingSenderId: '388102120008',
    projectId: 'fitlife-9c9f3',
    authDomain: 'fitlife-9c9f3.firebaseapp.com',
    storageBucket: 'fitlife-9c9f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb4nS2ggnVLvYjHLGgBl-5nXR6Ls99c0g',
    appId: '1:388102120008:android:8823b1e8791a788dbaae7d',
    messagingSenderId: '388102120008',
    projectId: 'fitlife-9c9f3',
    storageBucket: 'fitlife-9c9f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD__7GRxPl7GBkRpRDEED5aDkVZ0PbGO7U',
    appId: '1:388102120008:ios:c4f1a89c966ba6efbaae7d',
    messagingSenderId: '388102120008',
    projectId: 'fitlife-9c9f3',
    storageBucket: 'fitlife-9c9f3.firebasestorage.app',
    iosBundleId: 'com.example.fitlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD__7GRxPl7GBkRpRDEED5aDkVZ0PbGO7U',
    appId: '1:388102120008:ios:c4f1a89c966ba6efbaae7d',
    messagingSenderId: '388102120008',
    projectId: 'fitlife-9c9f3',
    storageBucket: 'fitlife-9c9f3.firebasestorage.app',
    iosBundleId: 'com.example.fitlife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2WRSrNT_amxU0SECjNsGtO2bUX-W7LjI',
    appId: '1:388102120008:web:0a59b5792ce439d3baae7d',
    messagingSenderId: '388102120008',
    projectId: 'fitlife-9c9f3',
    authDomain: 'fitlife-9c9f3.firebaseapp.com',
    storageBucket: 'fitlife-9c9f3.firebasestorage.app',
  );
}
